<a href="https://colab.research.google.com/github/ricecakeblack/practical-r/blob/main/10_Tensorflow_LowLevel_start.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

#### 아래 내용은 Tensorflow의 Low-Level API를 활용하기 위해 필요한 기본 내용입니다.

# **Tensor**

Tensor는 multi-dimensional array를 의미한다. TensorFlow의 기본 data type이다.

## **constant**
변하지 않는 숫자를 저장하는데 사용하는 텐서이다.

In [ ]:
# feature vector [1,2]를 tensorflow의 실수형 constant로 선언
feature = tf.constant([1,2], dtype=tf.float32)
print(feature)

tf.Tensor([1. 2.], shape=(2,), dtype=float32)


In [ ]:
x = tf.constant([[1.0, 2.0],
                 [3.0, 4.0]])
print(x)
print(type(x))

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [ ]:
## 아래와 같이 numpy ndarray나 python의 list도 tensor로 바꿀 수 있습니다
x_np = np.array([[1.0, 2.0],
                [3.0, 4.0]])
x_list = [[1.0, 2.0],
         [3.0, 4.0]]

print(type(x_np))
print(type(x_list))

<class 'numpy.ndarray'>
<class 'list'>


In [ ]:
# numpy array를 tensor로 변환
x_np = tf.convert_to_tensor(x_np)

# python 리스트를 tensor로 변환
x_list = tf.convert_to_tensor(x_list)

print(type(x_np))
print(type(x_list))

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [ ]:
# 이와는 반대로 tensor를 numpy array로 바꿀 수도 있다.
# pytorch를 따라(?)한 느낌?
x.numpy()

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [ ]:
print(type(x.numpy()))

<class 'numpy.ndarray'>


In [ ]:
# Tensor는 numpy ndarray처럼 dtype과 shape을 갖는다.
# 텐서의 type과 shape을 확인하려면
# "텐서.dtype", "텐서.shape"으로 가능하다.
print('dtype:', x.dtype)
print('shape:', x.shape)

dtype: <dtype: 'float32'>
shape: (2, 2)


In [ ]:
## 상수형 tensor를 생성하는 방법으로 아래와 같은 방법이 많이 사용됩니다
print(tf.ones(shape=(2,2))*0.2)
print(tf.zeros(shape=(2,2)))

tf.Tensor(
[[0.2 0.2]
 [0.2 0.2]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


In [ ]:
## tensor끼리의 4칙 연산은 element-wise 연산을 기본으로 합니다
a = tf.ones((2,2))*2
b = tf.ones((2,2))*6
print (a.numpy())
print (b.numpy())

[[2. 2.]
 [2. 2.]]
[[6. 6.]
 [6. 6.]]


In [ ]:
## 덧셈
print ("덧셈")
print (tf.add(a, b).numpy())
print ((a + b).numpy())

덧셈
[[8. 8.]
 [8. 8.]]
[[8. 8.]
 [8. 8.]]


In [ ]:
## 뺄셈
print ("뺄셈")
print (tf.subtract(b, a).numpy())
print ((b - a).numpy())

뺄셈
[[4. 4.]
 [4. 4.]]
[[4. 4.]
 [4. 4.]]


In [ ]:
## 곱셈
print ("곱셈")
print (tf.multiply(a, b).numpy())
print ((a * b).numpy())

곱셈
[[12. 12.]
 [12. 12.]]
[[12. 12.]
 [12. 12.]]


In [ ]:
## 나눗셈
print ("나눗셈")
print (tf.divide(b, a).numpy())
print ((b / a).numpy())

나눗셈
[[3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]]


In [ ]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[5,6],[7,8]])
print (a.numpy())
print (b.numpy())

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
## 행렬 곱 (matix multiplication)
print(tf.matmul(a, b).numpy())

[[19 22]
 [43 50]]


In [ ]:
## Tensor와 numpy ndarray는 많은 경우에 자동으로 호환된다.
ndarray = np.ones((3, 3))
print(ndarray)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
## Tensor연산에 입력으로 tensor가 아닌 ndarray가 입력으로 들어갈 수 있다.
print("numpy array를 tensor로 자동 변환")

# 행렬 값에 10을 곱한다.(broadcast연산)
tensor = tf.multiply(ndarray, 10)
print(tensor)

numpy array를 tensor로 자동 변환 
tf.Tensor(
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]], shape=(3, 3), dtype=float64)


In [ ]:
# numpy array연산에 tensor가 입력으로 들어갈 수 있다.
print(np.add(tensor, 2))

[[12. 12. 12.]
 [12. 12. 12.]
 [12. 12. 12.]]


In [ ]:
## Random한 상수형 tensor는 다음과 같이 만들 수 있습니다
## 아래는 표준정규분포로부터 상수를 생성합니다

rndConst = tf.random.normal(shape=(2,2), mean=0., stddev=1.)
rndConst

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.5757211 , -1.0655406 ],
       [-1.1987567 ,  0.05854351]], dtype=float32)>

## **Variables(변수)**

Variables는 변할 수 있는 값을 저장하는데 사용되는 텐서이다.

우리는 대부분의 경우에 우리가 학습해야하는 가중치(weight, parameter)들을 variable로 생성합니다.

In [ ]:
## 난수를 초기값으로 Variable을 생성할 수 있다.
initial_value = tf.random.normal(shape=(2, 2))
weight = tf.Variable(initial_value)
print(weight)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.10250378,  0.34411058],
       [ 0.394882  ,  0.9743154 ]], dtype=float32)>


In [ ]:
## 아래와 같이 variable을 초기화해주는 initializer들을 사용할 수도 있다.
## stddev : 표준 편차(standard deviation)
weight = tf.Variable(tf.random_normal_initializer(stddev=1.)(shape=(2,2)))
print(weight)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.08961298,  1.4418817 ],
       [ 1.558092  ,  0.26333913]], dtype=float32)>


In [ ]:
## variable은 '.assign(value)', '.assign_add(increment)', 또는 '.assign_sub(decrement)'
## 와 같은 메소드를 사용해서 Variable의 값을 갱신할 수 있다.

new_value = tf.random.normal(shape=(2,2))
print(new_value)
weight.assign(new_value)
print(weight)

tf.Tensor(
[[ 1.0268829 -0.4414104]
 [ 1.4484649  1.6602494]], shape=(2, 2), dtype=float32)
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 1.0268829, -0.4414104],
       [ 1.4484649,  1.6602494]], dtype=float32)>


In [ ]:
added_value = tf.ones(shape=(2,2))
weight.assign_sub(added_value)
print(weight)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.02688289, -1.4414104 ],
       [ 0.44846487,  0.66024935]], dtype=float32)>


## **Tensor Operations**

**Indexing, Slicing**

In [ ]:
x = tf.constant([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(x)

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)


In [ ]:
## indexing - indexing을 사용하면 항상 차원이 감소합니다
print(x[0])
print(x[1])
print(x[2])
print(x[0, 1])
print(x[1, 2])
print(x[2, 3])

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)
tf.Tensor([ 9 10 11 12], shape=(4,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)


In [ ]:
## slicing
print(x[2:, 3:])
print(x[:2, 1:3])
print(x[1:3, 3:])

tf.Tensor([[12]], shape=(1, 1), dtype=int32)
tf.Tensor(
[[2 3]
 [6 7]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 8]
 [12]], shape=(2, 1), dtype=int32)


**Reshape**

In [ ]:
t = tf.constant([[[0, 1, 2],
                [3, 4, 5]],
               [[6, 7, 8],
                [9, 10, 11]]])
print(t.shape)

(2, 2, 3)


In [ ]:
print(tf.reshape(t, shape=[-1, 3]))

tf.Tensor(
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]], shape=(4, 3), dtype=int32)


In [ ]:
print(tf.reshape(t, shape=[-1, 1, 3]))

tf.Tensor(
[[[ 0  1  2]]

 [[ 3  4  5]]

 [[ 6  7  8]]

 [[ 9 10 11]]], shape=(4, 1, 3), dtype=int32)


**Reduce Mean/Sum**

In [ ]:
x = tf.constant([[1., 2.],
                [3., 4.]])

print(x)
print(tf.reduce_mean(x))

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(2.5, shape=(), dtype=float32)


In [ ]:
# 행간의 데이터를 더해서 평균을 구한다.
print(tf.reduce_mean(x, axis=0))

tf.Tensor([2. 3.], shape=(2,), dtype=float32)


In [ ]:
# 한 행의 Feature Vector의 평균을 구한다.
print(tf.reduce_mean(x, axis=1))


tf.Tensor([1.5 3.5], shape=(2,), dtype=float32)


In [ ]:
print(tf.reduce_mean(x, axis=-1))


tf.Tensor([1.5 3.5], shape=(2,), dtype=float32)


**Argmax**

In [ ]:
x = [[3, 4, 5],
     [5, 4, 3]]
print(x)
print(tf.argmax(x, axis=0))

[[3, 4, 5], [5, 4, 3]]
tf.Tensor([1 0 0], shape=(3,), dtype=int64)


In [ ]:
print(tf.argmax(x, axis=1))

tf.Tensor([2 0], shape=(2,), dtype=int64)


In [ ]:
print(tf.argmax(x, axis=-1))

tf.Tensor([2 0], shape=(2,), dtype=int64)


**One-hot Encoding**

In [ ]:
label = tf.constant([0, 1, 2, 0])
onehot1 = tf.one_hot(label, depth=3)
onehot2 = keras.utils.to_categorical(label, num_classes=3)

print(onehot1, type(onehot1))
print(onehot2, type(onehot2))

**Type Casting**

In [ ]:
print(tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32))

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [ ]:
print(tf.cast([True, False, 1 == 1, 0 == 1], tf.int32))

tf.Tensor([1 0 1 0], shape=(4,), dtype=int32)


## **tf.data를 이용하여 Dataset 만들기**

TensorFlow를 이용하여 deep learning model을 학습할 때, input data 및 label을 공급해주기 위하여 tf.data.Dataset을 이용합니다.

In [ ]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
## 0에서 9까지 정수가 input data라고 가정해봅시다
a = np.arange(10)
print(a)

## dataset은 아래와 같이 만들 수 있습니다
ds_tensors = tf.data.Dataset.from_tensor_slices(a)
print(ds_tensors)

[0 1 2 3 4 5 6 7 8 9]
<TensorSliceDataset shapes: (), types: tf.int64>


In [ ]:
## dataset에서 앞 5개 data를 꺼내서 확인해보겠습니다
#data = ds_tensors.take(5)
for x in ds_tensors:
    print (x)
    #model(x)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)


In [ ]:
## dataset 내의 각 data에 함수를 적용하기 위해서는 아래와 같이 map을 사용합니다
## 이는 data 전처리에 많이 사용됩니다
## 또한 data를 섞어주는 shuffle과 batch size만큼 data를 꺼내주는 batch도 사용할 수 있습니다

ds_tensors = ds_tensors.map(tf.square).shuffle(10).batch(2)

In [ ]:
## 실제 data를 꺼내서 사용할 때는 아래와 같이 for문에 dataset을 넣어주면 됩니다.
print('Elements of ds_tensors:')
print('='*50)
for _ in range(3):
    for x in ds_tensors:
        print(x)
    print('='*50)

Elements of ds_tensors:
tf.Tensor([ 4 49], shape=(2,), dtype=int64)
tf.Tensor([0 9], shape=(2,), dtype=int64)
tf.Tensor([36 64], shape=(2,), dtype=int64)
tf.Tensor([25 81], shape=(2,), dtype=int64)
tf.Tensor([ 1 16], shape=(2,), dtype=int64)
tf.Tensor([0 9], shape=(2,), dtype=int64)
tf.Tensor([36 49], shape=(2,), dtype=int64)
tf.Tensor([16 25], shape=(2,), dtype=int64)
tf.Tensor([ 4 81], shape=(2,), dtype=int64)
tf.Tensor([64  1], shape=(2,), dtype=int64)
tf.Tensor([25  0], shape=(2,), dtype=int64)
tf.Tensor([ 4 49], shape=(2,), dtype=int64)
tf.Tensor([81  1], shape=(2,), dtype=int64)
tf.Tensor([64  9], shape=(2,), dtype=int64)
tf.Tensor([16 36], shape=(2,), dtype=int64)


## TensorFlow를 이용하여 자동미분 계산하기
Deep learning model을 학습시키기 위해서는 gradient descent 방법을 사용하고, 이를 위해서는 gradient 즉 미분을 계산해야 합니다. (Loss 를 weight로 미분)

TensorFlow에서 자동으로 미분을 계산하는 방법을 알아보겠습니다

TensorFlow는 자동 미분을 위한 tf.GradientTape API를 제공합니다.

tf.GradientTape는 컨텍스트(context) 안에서 실행된 모든 연산을 테이프(tape)에 "기록"합니다.

그 다음 TensorFlow는 후진 방식 자동 미분(reverse mode differentiation)을 사용해 테이프에 "기록된" 연산의 그래디언트를 계산합니다.

In [ ]:
## GradientTape를 열게되면, 그때부턴 tape.watch()를 통해 tensor를 확인하고,
## 이 tensor를 입력으로써 사용하는 미분을 자동으로 계산하는것이 가능합니다.

## x = 3
x = tf.ones((1,))*3

with tf.GradientTape() as t:
    t.watch(x)
    y = tf.square(x)

# 입력 텐서 x에 대한 미분
dy_dx = t.gradient(y, x)
print(dy_dx)

tf.Tensor([6.], shape=(1,), dtype=float32)


In [ ]:
## 기본적으로 Variable들은 자동으로 watch가 적용되어 있기 때문에, 수동으로 `watch`를 해 줄 필요는 없습니다.
x = tf.Variable(x)

with tf.GradientTape() as t:
    y = tf.square(x)

# 입력 텐서 x에 대한 z의 미분
dy_dx = t.gradient(y, x)
print(dy_dx)

tf.Tensor([6.], shape=(1,), dtype=float32)
